/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shoppingbasketkata;

import org.junit.jupiter.api.DisplayNameGeneration;
import org.junit.jupiter.api.DisplayNameGenerator;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
class ShoppingBasketTest {
    @Test void blah() {
        assertTrue(false);
    }
}
